### ISSUE TITLE
Add python 3 compatibility

### ISSUE THREAD

**Issue by cosinequanon** [lyft/high-entropy-string#8]
This library says it's only python 2 compatible but that will soon be deprecated. We should make this work with python 3 too (maybe it does already?)

**Comment by anupsv** [comment]
It looks like zxcvbn is causing problems from being imported to python 3. I am interested in this library, so i might take some time and port it to python 3.

**Comment by khanhldt** [comment]
Closing this issue as Lyft team is deprecating this repository.
